<script src="https://cdn.tailwindcss.com"></script>
<?php
$cate = $block->getCategory();
$posts = $block->getCategoryPosts();

if (!empty($cate)):
    ?>
    <div>
        <h1 class="text-[30px] font-bold mb-4 pt-4">Thông tin category</h1>
        <div class="bg-white p-4 border border-gray-200 rounded-lg shadow-lg">
            <h2 class="text-xl font-bold mb-2">
                <?= $cate->getName(); ?>
            </h2>
            <img src="https://a.slack-edge.com/9c84081/marketing/img/solutions/tech/png/billboard.png"
                class="w-full h-48 object-cover mt-2 rounded-lg" alt="Profile Image">
            <p><?= $cate->getDescription(); ?></p>
        </div>
    </div>
    <div class="mt-10">
        <h1 class="text-[30px] font-bold mb-4 pt-4">Các bài viết</h1>
        <div id="card-container" class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 p-4">
            <?php foreach ($posts as $post): ?>
                <div class="bg-white p-4 border border-gray-200 rounded-lg shadow-lg">
                    <h2 class="text-xl font-bold mb-2">
                        <a
                            href="/tigrenblog_fe/DetailPost/index?post_id=<?= $post->getPostId(); ?>"><?= $post->getTitle(); ?></a>
                    </h2>
                    <img src=" <?= $post->getPostImage(); ?>" class="w-full h-48 object-cover mt-2 rounded-lg"
                        alt="Profile Image">
                </div>
            <?php endforeach; ?>
        </div>
    </div>
<?php else: ?>
    <p>No Cate found.</p>
<?php endif; ?>